# Generated by Django 5.0.3 on 2024-03-25 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('tipo1', models.CharField(max_length=50)),
                ('tipo2', models.CharField(max_length=50, null=True)),
                ('numero', models.IntegerField()),
                ('descricao', models.CharField(max_length=200)),
                ('imagem', models.CharField(default=None, max_length=50, null=True)),
            ],
        ),
    ]
