# Generated by Django 5.0.3 on 2024-03-25 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokedex', '0002_remove_pokemon_imagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokemon',
            name='numero',
            field=models.CharField(max_length=50),
        ),
    ]
